name: Codecov

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run devnet:start
      - run: npm test
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          name: codecov-alephium-js
          fail_ci_if_error: true
