name: OpenAPI Test

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run fetch-schema:alephium && test -z "$(git status --porcelain)"
      - run: npm run fetch-schema:explorer && test -z "$(git status --porcelain)"
